# Generated by Django 6.0.5 on 2026-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coursecategory_course_is_published_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/', verbose_name='上傳影片檔'),
        ),
    ]
