# Generated by Django 6.0.5 on 2026-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_courselesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='繳費期限'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='超商繳費代碼'),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ATM 虛擬帳號'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', '信用卡'), ('atm', 'ATM 虛擬帳號轉帳'), ('cvs', '超商代碼繳費'), ('line_pay', 'LINE Pay'), ('cash', '現金'), ('mock', '模擬付款')], default='mock', max_length=30, verbose_name='付款方式'),
        ),
    ]
