# Generated by Django 6.0.5 on 2026-07-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_expire_at_payment_payment_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_map', models.TextField(blank=True, default='', verbose_name='已觀看秒圖')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='累積觀看秒數')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='上次觀看位置(秒)')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='影片總長(秒)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='課程')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courselesson', verbose_name='單元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '單元觀看進度',
                'verbose_name_plural': '單元觀看進度',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
