# Generated by Django 6.0.5 on 2026-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='折扣價（選填，需低於原價）'),
        ),
        migrations.AddField(
            model_name='course',
            name='early_bird_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='早鳥優惠價（募資期間適用，需低於原價）'),
        ),
        migrations.AddField(
            model_name='course',
            name='funding_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='募資結束時間'),
        ),
        migrations.AddField(
            model_name='course',
            name='funding_goal',
            field=models.PositiveIntegerField(default=0, verbose_name='募資門檻人數'),
        ),
        migrations.AddField(
            model_name='course',
            name='funding_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='募資開始時間'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_crowdfunding',
            field=models.BooleanField(default=False, verbose_name='是否為募資課程'),
        ),
    ]
