# Generated by Django 6.0.5 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_course_access_duration_days_course_intro_video_file_and_more'),
    ]

    # 這支 migration 在共用雲端資料庫上已經標記為套用過（當時 main_orderitem
    # 是由另一位組員直接對共用 DB 加欄位，這裡只補 Django 的狀態，沒有真的
    # ALTER TABLE），所以以下改動不會影響共用 DB —— migration 只認名稱，
    # 已套用過的不會重跑。但全新資料庫（CI、測試、新同伴 clone）從頭跑
    # migrate 時需要真的建出這兩欄，所以改回正常的 AddField。
    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='此項折扣金額'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='此項實付金額'),
        ),
    ]
