# Generated by Django 4.2.30 on 2026-07-31 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_orderitem_discount_amount_orderitem_paid_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherBankAccount',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='提領金額')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('completed', '已完成'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, null=True, verbose_name='處理備註')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='講師')),
            ],
            options={
                'verbose_name': '提領紀錄',
                'verbose_name_plural': '提領紀錄',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.PositiveIntegerField(verbose_name='實付金額')),
                ('marketing_cost', models.PositiveIntegerField(default=0, verbose_name='行銷成本')),
                ('teacher_split_percent', models.PositiveSmallIntegerField(verbose_name='講師分潤比例(%)')),
                ('company_split_percent', models.PositiveSmallIntegerField(verbose_name='公司分潤比例(%)')),
                ('teacher_marketing_share_percent', models.PositiveSmallIntegerField(verbose_name='講師行銷成本負擔比例(%)')),
                ('company_marketing_share_percent', models.PositiveSmallIntegerField(verbose_name='公司行銷成本負擔比例(%)')),
                ('teacher_amount', models.IntegerField(default=0, verbose_name='講師應付金額')),
                ('company_amount', models.IntegerField(default=0, verbose_name='公司實收金額')),
                ('status', models.CharField(choices=[('confirmed', '已確認'), ('reversed', '已沖銷（退款）')], default='confirmed', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='沖銷時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='main.course', verbose_name='課程')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='main.order', verbose_name='訂單')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_record', to='main.orderitem', verbose_name='訂單明細')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to=settings.AUTH_USER_MODEL, verbose_name='講師')),
            ],
            options={
                'verbose_name': '收支分潤紀錄',
                'verbose_name_plural': '收支分潤紀錄',
            },
        ),
        migrations.CreateModel(
            name='CourseSplitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_split_percent', models.PositiveSmallIntegerField(default=70, verbose_name='講師分潤比例(%)')),
                ('company_split_percent', models.PositiveSmallIntegerField(default=30, verbose_name='公司分潤比例(%)')),
                ('teacher_marketing_share_percent', models.PositiveSmallIntegerField(default=50, verbose_name='講師負擔行銷成本比例(%)')),
                ('company_marketing_share_percent', models.PositiveSmallIntegerField(default=50, verbose_name='公司負擔行銷成本比例(%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_setting', to='main.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '課程分潤設定',
                'verbose_name_plural': '課程分潤設定',
            },
        ),
    ]
